openapi: 3.0.0

info:
  title: Get Virus Total IP Information
  description: Get Information about an IP from Virus Total
  version: "v1"

servers:
  - url: https://www.virustotal.com/api

paths:
  /v3/ip_addresses/{ip}:
    get:
      operationId: getVirusTotalIP
      summary: Get Virus Total IP Information for a particular IP address
      parameters:
        - in: path
          name: ip
          schema:
            type: string
          required: true
          description: The IP address to lookup
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getVTIPResponse"
        "401":
          description: Unauthorized - Invalid API key

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-apikey
  schemas:
    getVTIPResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: string
            attributes:
              type: object
