openapi: 3.0.0

info:
  title: Get Virus Total IP Information
  description: Get Information about an IP from Virus Total
  version: "v1"

servers:
  - url: https://www.virustotal.com/api

paths:
  /v3/ip_addresses/{ip}:
    get:
      operationId: getVirusTotalIP
      summary: Get Virus Total IP Information for a particular IP address
      parameters:
        - in: path
          name: ip
          schema:
            type: string
          required: true
          description: The IP address to lookup
        - in: header
          name: X-Apikey
          schema:
            type: string
          required: true
          description: VirusTotal API key
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getVTIPResponse"

components:
  schemas:
    getVTIPResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            attributes:
              type: object
              properties:
                last_analysis_stats:
                  type: object
                  properties:
                    harmless:
                      type: integer
                    malicious:
                      type: integer
                    suspicious:
                      type: integer
                    undetected:
                      type: integer
                last_analysis_results:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      category:
                        type: string
                      result:
                        type: string
                      method:
                        type: string
                      engine_name:
                        type: string
                reputation:
                  type: integer
                country:
                  type: string
                asn:
                  type: integer
                as_owner:
                  type: string
                jarm:
                  type: string
                network:
                  type: string
                last_https_certificate_date:
                  type: integer
                tags:
                  type: array
                  items:
                    type: string
