openapi: 3.0.0
info:
  title: VirusTotal URL API
  description: Submit URLs for scanning and retrieve reputation and analysis details from VirusTotal.
  version: v1
servers:
  - url: https://www.virustotal.com/api
paths:
  /v3/urls:
    post:
      operationId: submitVirusTotalURL
      summary: Submit a raw URL to VirusTotal for scanning and get its encoded ID.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  description: The raw URL to submit (e.g., https://example.com).
                  example: "https://example.com"
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  description: The raw URL to submit (e.g., https://example.com).
                  example: "https://example.com"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postVTURLResponse"
              examples:
                submitExample:
                  summary: Submit URL example
                  value:
                    data:
                      type: "analysis"
                      id: "aHR0cHM6Ly9leGFtcGxlLmNvbQ"
          links:
            GetSubmittedUrlAnalysis:
              operationId: getVirusTotalURL
              description: Use the returned id to retrieve the latest analysis and reputation details.
              parameters:
                id: "$response.body#/data/id"
  /v3/urls/{id}:
    get:
      operationId: getVirusTotalURL
      summary: Get VirusTotal URL Information for a specific URL.
      parameters:
        - $ref: "#/components/parameters/UrlIdParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getVTURLResponse"
              examples:
                lookupExample:
                  summary: Lookup URL by encoded id
                  value:
                    data:
                      type: "url"
                      id: "aHR0cHM6Ly9leGFtcGxlLmNvbQ"
                      attributes:
                        last_analysis_stats:
                          harmless: 70
                          malicious: 5
                          suspicious: 2
                          undetected: 10
                        reputation: -50
                        tags: ["phishing", "malware"]
                        categories:
                          Security: "Malware"
                        last_submission_date: 1672531200
components:
  parameters:
    UrlIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
      description: The URL identifier (must be base64 encoded without padding; returned by POST /v3/urls).
  schemas:
    postVTURLResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              example: "analysis"
            id:
              type: string
              description: Encoded URL identifier (use this for GET lookup)
              example: "aHR0cHM6Ly9leGFtcGxlLmNvbQ"
    getVTURLResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              example: "url"
            id:
              type: string
              description: Base64-encoded URL identifier
            attributes:
              type: object
              properties:
                last_analysis_stats:
                  type: object
                  properties:
                    harmless:
                      type: integer
                      example: 70
                    malicious:
                      type: integer
                      example: 5
                    suspicious:
                      type: integer
                      example: 2
                    undetected:
                      type: integer
                      example: 10
                last_analysis_results:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      category:
                        type: string
                        example: "malicious"
                      result:
                        type: string
                        example: "malware"
                      engine_name:
                        type: string
                        example: "Kaspersky"
                reputation:
                  type: integer
                  description: Reputation score (-100 to 100)
                  example: -50
                tags:
                  type: array
                  items:
                    type: string
                  example: ["phishing", "malware"]
                categories:
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    "Security": "Malware"
                last_submission_date:
                  type: integer
                  description: Unix timestamp of last submission
